### ISSUE TITLE
Error when loading the model

### ISSUE THREAD

**Issue by SiddhantKumar-Dev** [EricAlcaide/MiniFold#45]
Currently I am using this code to load the model:
**model = keras.models.load_model("tester_28_lxl.h5")**

However, when I am loading this I'm getting this error.
```

Traceback (most recent call last):
  File "pretrain_model_pssm_l_x_l.py", line 255, in <module>
    model2 = keras.models.load_model("tester_28_lxl.h5")
  File "/Users/sid/opt/anaconda3/envs/mini_fold/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 207, in load_model
    compile)
  File "/Users/sid/opt/anaconda3/envs/mini_fold/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 184, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/Users/sid/opt/anaconda3/envs/mini_fold/lib/python3.7/site-packages/tensorflow/python/keras/saving/model_config.py", line 64, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/Users/sid/opt/anaconda3/envs/mini_fold/lib/python3.7/site-packages/tensorflow/python/keras/layers/serialization.py", line 177, in deserialize
    printable_module_name='layer')
  File "/Users/sid/opt/anaconda3/envs/mini_fold/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 358, in deserialize_keras_object
    list(custom_objects.items())))
  File "/Users/sid/opt/anaconda3/envs/mini_fold/lib/python3.7/site-packages/tensorflow/python/keras/engine/functional.py", line 669, in from_config
    config, custom_objects)
  File "/Users/sid/opt/anaconda3/envs/mini_fold/lib/python3.7/site-packages/tensorflow/python/keras/engine/functional.py", line 1275, in reconstruct_from_config
    process_layer(layer_data)
  File "/Users/sid/opt/anaconda3/envs/mini_fold/lib/python3.7/site-packages/tensorflow/python/keras/engine/functional.py", line 1257, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/Users/sid/opt/anaconda3/envs/mini_fold/lib/python3.7/site-packages/tensorflow/python/keras/layers/serialization.py", line 177, in deserialize
    printable_module_name='layer')
  File "/Users/sid/opt/anaconda3/envs/mini_fold/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 360, in deserialize_keras_object
    return cls.from_config(cls_config)
  File "/Users/sid/opt/anaconda3/envs/mini_fold/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 720, in from_config
    return cls(**config)
  File "/Users/sid/opt/anaconda3/envs/mini_fold/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py", line 437, in __init__
    self.activation = activations.get(activation)
  File "/Users/sid/opt/anaconda3/envs/mini_fold/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/Users/sid/opt/anaconda3/envs/mini_fold/lib/python3.7/site-packages/tensorflow/python/keras/activations.py", line 573, in get
    return deserialize(identifier)
  File "/Users/sid/opt/anaconda3/envs/mini_fold/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/Users/sid/opt/anaconda3/envs/mini_fold/lib/python3.7/site-packages/tensorflow/python/keras/activations.py", line 536, in deserialize
    printable_module_name='activation function')
  File "/Users/sid/opt/anaconda3/envs/mini_fold/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 378, in deserialize_keras_object
    'Unknown ' + printable_module_name + ': ' + object_name)
ValueError: Unknown activation function: softMaxAxis2

```
Ultimately the error says that there is an unknown activation function: softMaxAxis2.
I am not sure what is causing this issue.

**Comment by SiddhantKumar-Dev** [comment]
When loading the model, I needed to mention the custom_objects, and incorporate those functions into the file.
model= keras.models.load_model("tester_28_lxl.h5", custom_objects = {"loss": loss, "softMaxAxis2":(softMaxAxis2)})
